### ISSUE TITLE
Not reading Clipboard on Linux/KDE

### ISSUE THREAD

**Issue by Gfurst** [marisukukise/japReader#2]
Hello there, first trying out this helpful app. Seemingly installed fine and works without error, but just sits there regardless of what text is copied to clipboard. Is there anything I'm missing?

**Comment by marisukukise** [comment]
The app should only detect Japanese text. Are you copying Japanese text or English?
Also do you get any errors in console after the 
```
> japanese-reader@1.3.2 start
> electron .
```
message?
The reader window should have text like this on startup:
![02：33：45 (3035)](https://user-images.githubusercontent.com/109931938/184460276-e42dc71a-6d8f-4e16-99c4-e526537337e3.png)

And then it should detect Japanese text from the clipboard.

**Comment by Gfurst** [comment]
Thanks, yes it shows exactly that window, nothing of note after that message,  `npm start  4,90s user 1,08s system 22% cpu 26,504 total`.

And yes, copying japanese text, proper kana and kanji. Unless there is some clipboard protection system that I'm unaware of, why I mentioned the KDE desktop.

**Comment by marisukukise** [comment]
In your files try changing this line in script.js:
https://github.com/marisukukise/japReader/blob/3ff5d263aa3ecf9911806878daaa4c72390f400d/boxes/clipboard/script.js#L28
to
```js
if (os.platform() === 'darwin' || os.platform() === 'linux') {
```

**Comment by Gfurst** [comment]
Brilliant, that worked out. Many thanks

**Comment by marisukukise** [comment]
will close the issue when I fix it "officially" in the future (or not)
locking for now

**Comment by marisukukise** [comment]
In the version v1.5.1: https://github.com/marisukukise/japReader/releases/tag/v1.5.1
the clipboard reading should be improved. The solution before was kind of hacky and temporary, as it looked for changes in clipboard every 0.5s. But on v1.5.1, if you install a package it should update immediately on clipboard change.
