### ISSUE TITLE
[BUG] Translation window for Deepl stuck on "Please wait patiently..."

### ISSUE THREAD

**Issue by Ashdemai** [marisukukise/japReader#56]
**Describe the bug**
Program fails to connect to DeepL like it had previously. I was not using an API key.
**To Reproduce**
Launch program, wait for DeepL to connect

**Expected behavior**
It should say it connected to the DeepL server

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch
 - Version: latest

**Additional context**

**Comment by Ashdemai** [comment]
Is it location based? It happens both on my desktop and laptop. It just doesn't want connect successfully. On the other hand, if I go directly to deepl's site, it loads fine that way. I'm just confused.

**Comment by Ashdemai** [comment]
> By latest do you mean 1.9.1 version or 2.0.0-beta?

Sorry, hadn't mentioned it. I still use 1.9.1

Here's an image of the settings.

I'll give your debug suggestion a try and tell you if I find something.
![Screenshot from 2023-09-17 07-11-48](https://github.com/marisukukise/japReader/assets/74661175/54ab5c12-0677-4b1d-a0ea-263de9413ae6)

**Comment by Gfurst** [comment]
It was working for me till today, now I'm getting stuck with no response from deepl as well, even tho I can open the site just fine. (updated the app just now)

**Comment by Ashdemai** [comment]
I don't know what to tell you guys, but for some reason it started working for me again. I literally did nothing to fix it. I also tried the debugging mode when it wasn't working and the open deepl site was working so I have no clue what caused the program side to not show anything.

Should I close this issue?

**Comment by Gfurst** [comment]
>So for now you can enable the DeepL API in options, make a DeepL account and use the DeepL API key

I was hoping to do this, but for some reason deepl doesn't show me any API key, I think because my country isn't available in the premium plans, they don't even offer the free API.

**Comment by Gfurst** [comment]
Perfect!

**Comment by Ashdemai** [comment]
I think this solved the issue. I'm going to close this now.
